Misc:
  GpuId: 0
  OutputFolderName: 'df1b'
  BestModelName: 'model_seg.pth'

Model:
  Name: 'unet'
  Encoder: 'resnet18'
  EncoderWeights: 'imagenet'
  Activation: 'sigmoid'
  NumClass: 1
  IsResume: False
  OutputFreq: 5


Dataset:
  TrainPath: '/home/pi/Desktop/df1b_dataset/20191017/train/'
  TestPath: '/home/pi/Desktop/df1b_dataset/20191017/train/'
  BatchSize: 2
  NumWorkers: 1
  Epochs: 100

Solver:
  OptimName: 'sgd'
  BaseLR: 0.05
  WeightDecay: 0.0005
  BiasLRFactor: 2
  WeightDecayBias: 0.0
  WarnupIters: 500
  SchedulerModel: 'poly'
  LossName: 'bcedice'
